kind: pipeline
type: exec
name: test-exec

platform:
  os: linux
  arch: amd64

steps:
- name: greeting
  commands:
  - echo hello world
  - export
  - ls /home
  - pwd
  - ls -l /usr/local/
  - curl ipconfig.io